# Generated by Django 5.2.17 on 2026-09-14 10:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.profiles.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("birth_date", models.DateField()),
                ("policy_version", models.CharField(max_length=64)),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="private_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "alias",
                    models.CharField(
                        default=apps.profiles.models.new_alias, editable=False, max_length=64, unique=True
                    ),
                ),
                ("avatar_id", models.CharField(max_length=32)),
                ("gender", models.CharField(max_length=24)),
                ("intentions", models.JSONField(default=list)),
                ("interests", models.JSONField(default=list)),
                ("languages", models.JSONField(default=list)),
                ("conversation_style", models.CharField(max_length=24)),
                ("prompt_answer", models.CharField(blank=True, max_length=280)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("genders", models.JSONField(default=list)),
                ("min_age", models.PositiveSmallIntegerField(default=18)),
                ("max_age", models.PositiveSmallIntegerField(default=120)),
                ("open_chat_opt_in", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("min_age__gte", 18)), name="matching_adults_only"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_age__lte", 120)), name="matching_age_upper_bound"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_age__gte", models.F("min_age"))), name="matching_age_order"
                    ),
                ],
            },
        ),
    ]
