# Generated by Django 5.2.17 on 2026-09-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_random_chat_adult_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='discoverable',
            field=models.BooleanField(default=False),
        ),
    ]
