# Generated by Django 5.2.17 on 2026-09-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginchallenge',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
